### ISSUE TITLE
libarchive is using lzma static (I think)

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/libarchive-feedstock#25]
I know this is not anything you guys are doing, but my builds on aarch64, in a pretty stripped down container are failing to find:

```
  CCLD     libarchive_fe.la
/usr/bin/grep: /root/archiconda3/conda-bld/libarchive_1546902350185/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/liblzma.la: No such file or directory
```

My feeling is that it is trying to statically link to it, but can't find it.

Here is a build for example that shows the whole process.

https://app.shippable.com/github/Archiconda/libarchive-feedstock/runs/8/1/console

when jjhelmus made his bootstrap packages, with conda-build in oct 2018, that can be found 
https://anaconda.org/jjhelmus/repo?label=aarch64_bootstrap
you can see that the liblzma.la file is included in the xz library, which is why I think he was able to compile libarchive. 

My feedstock:
https://github.com/archiconda/libarchive-feedstock

**Comment by mingwandroid** [comment]
conda-build removes .la files now to prevent them from getting used (many Linux distros take this approach). I'm not sure why the build is not being clever enough to avoid `.la` files here. Can you search in `$SRC_DIR` for any occurrence of `liblzma.la`?

**Comment by hmaarrfk** [comment]
yeah, you are right, that file doesn't exist on amd64 and it is building fine. I'm trying out a few different compilation options now, but iteration time is slow, because qemu is slow. thanks for chiming in.

**Comment by hmaarrfk** [comment]
for reference, their docs seem to imply that they are preferring to use static linking
https://github.com/libarchive/libarchive/wiki/BuildInstructions

**Comment by mingwandroid** [comment]
Mmm, they prefer linking statically to their own libs for their own programs (tar, cpio) but I don't know that that extends to the transitive deps that do the actual low level {de,}compression. It might mind you as *not* doing it that way would require some build system gynmastics.

**Comment by hmaarrfk** [comment]
hmmm the only thing I can think of, is that it found `libxml2.la`, which was left over from conda 3.15 and assumed it could recompile everything statically. 

I'm recompiling that, but qemu likes to take its time and shippable is working hard on scipy....

**Comment by hmaarrfk** [comment]
Yeah ok, that was it. Thanks for bouncing ideas @mingwandroid !!!

I should have just followed the build order.....
