### ISSUE TITLE
CircleCI not uploading

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libarchive-feedstock#3]
It appears this is not uploading on CircleCI. This is a bit weird. Though we have seen this in one other case. Getting some more eyes on this would help. @pelson, any ideas why this doesn't upload?

**Comment by jakirkham** [comment]
Now that I have disabled `make check`. This built and uploaded. So, there must be something happening during `make check` on our Linux builds that is blocking the release. Not sure what that is. Until we figure it out, would like to leave that disabled.

**Comment by pelson** [comment]
Similar symptoms to https://github.com/conda-forge/erlang-feedstock/issues/1. Does a similar fix exist there too?

**Comment by jakirkham** [comment]
Like skipping the tests. Possibly, it can always be tried. Though I don't think this is our most pressing issue. Unpinning `conda-build` on Travis CI is. See this issues ( https://github.com/conda-forge/hdf5-feedstock/issues/23 ) to get an idea of what I mean.

**Comment by jakirkham** [comment]
Going to close as this is resolved.
