### ISSUE TITLE
Most recent release on Linux 64 breaks conda

### ISSUE THREAD

**Issue by langmm** [conda-forge/libarchive-feedstock#38]
Issue:

After the release to conda-forge ~20min ago for Linux 64 (PR #37), updating conda (`conda update -q conda`) (following a clean install) yields the following error:

```
OSError: libiconv.so.2: cannot open shared object file: No such file or directory
```

For a full comparison before and after the update you can see my CI builds [here (before)](https://api.travis-ci.org/v3/job/567654340/log.txt) and [here (after)](https://api.travis-ci.org/v3/job/567976952/log.txt).

I do not have an output of conda info as the error occurs during initial call to update conda, but the only changes called where to add the conda-forge channel and set the channel_priority to strict. Otherwise, this is a completely fresh install of Miniconda3.

This looks to be an issue with the dependency on libiconv (referenced in #35) being dropped in the recent PR.

**Comment by ocefpaf** [comment]
I believe that the culprit is https://github.com/conda-forge/libxml2-feedstock/pull/48

I pulled the `libxml2` build number `3` and this should be back to normal soon.

**Comment by langmm** [comment]
Ah yes, I was able to run now. Thanks and sorry for the noise!

**Comment by ocefpaf** [comment]
> Ah yes, I was able to run now. Thanks and sorry for the noise!

That is not noise! Thanks for the report. We are working on a way to roll that change with minimal disruption, maybe we'll try during the weekend and hopefully re-build everything without breaking people CIs.

**Comment by beckermr** [comment]
@ocefpaf I am still seeing an error that looks like this one. However, I am on build 2 of libxml2 and the old build of libarchive. Any ideas?

My CI build is here: https://travis-ci.org/LSSTDESC/CCL/jobs/568123856

**Comment by beckermr** [comment]
I think this has been solved.

**Comment by ocefpaf** [comment]
I think @isuruf removed the build number 2 (two package got uploaded in https://github.com/conda-forge/libxml2-feedstock/pull/48.)
